type Summary = {
  signalSystemStatus: string; activeSignals: number; eligibleObservations: number; rejectedObservations: number; detectedObservations: number; resolvedSignals: number; expiredSignals: number; latestSignalCronAt: string | null; latestOpportunityCronAt: string | null; latestDecision: string | null; latestDecisionReason: string | null; externalReference: { available: boolean; provider: string | null; fetchedAt: string | null; ageMs: number | null; error: string | null }; rejectionBreakdown: Array<{ decision: string; count: number }>;
};
function ago(value: string | null) { if (!value) return "Not recorded"; const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 1 ? "Just now" : `${minutes} min ago`; }
export function SignalsDiagnostics({ summary }: { summary: Summary | null }) {
  if (!summary) return <div className="diagnosticsLoading">Loading Signals diagnostics…</div>;
  return <section className="signalsDiagnostics" aria-labelledby="signals-diagnostics-title">
    <div className="diagnosticsHeader"><div><span className="sectionEyebrow">PIPELINE DIAGNOSTICS</span><h2 id="signals-diagnostics-title">{summary.signalSystemStatus}</h2><p>Counts come from persisted research observations and Signals records. No records are fabricated for display.</p></div><span className={`diagnosticsStatus ${summary.externalReference.available ? "isGood" : "isWarn"}`}>{summary.externalReference.available ? "External reference available" : "External reference unavailable"}</span></div>
    <div className="diagnosticsGrid">
      <div><span>Active signals</span><strong>{summary.activeSignals}</strong></div><div><span>Eligible observations</span><strong>{summary.eligibleObservations}</strong></div><div><span>Rejected observations</span><strong>{summary.rejectedObservations}</strong></div><div><span>Detected observations</span><strong>{summary.detectedObservations}</strong></div><div><span>Resolved signals</span><strong>{summary.resolvedSignals}</strong></div><div><span>Expired signals</span><strong>{summary.expiredSignals}</strong></div><div><span>Signals cron</span><strong>{ago(summary.latestSignalCronAt)}</strong></div><div><span>Opportunity cron</span><strong>{ago(summary.latestOpportunityCronAt)}</strong></div>
    </div>
    <div className="diagnosticsDetails"><div><b>External reference</b><span>{summary.externalReference.available ? `${summary.externalReference.provider ?? "Provider"} · ${ago(summary.externalReference.fetchedAt)}` : summary.externalReference.error ?? "Independent external reference unavailable"}</span></div><div><b>Latest rejection</b><span>{summary.latestDecision ? `${summary.latestDecision} · ${summary.latestDecisionReason ?? "No reason recorded"}` : "No observations yet"}</span></div><div><b>Lifecycle</b><span>Prices → opportunity cron → research observations → Signals cron → Signals. LONG spread research only; SELL/SHORT is directional evidence, not executable.</span></div></div>
  </section>;
}
