import type { ObjectId } from "mongodb";
import type { OpportunityAnalysis } from "../opportunity/types";
export type SignalStatus = "ACTIVE" | "EXPIRED" | "RESOLVED" | "INVALIDATED";
export type SignalRoute = "LONG_SPREAD" | "REVERSE_SHORT_SPREAD" | "PORTFOLIO_EXIT";
export type SignalActualResult = "TARGET_REACHED" | "INVALIDATED" | "EXPIRED" | null;
export type SignalDocument = {
  _id?: ObjectId;
  signalKey: string;
  status: SignalStatus;
  detectedAt: Date;
  expiresAt: Date;
  sourceResearchObservationId: ObjectId;
  sourceOpportunityId: ObjectId | null;
  paperPositionId: ObjectId | null;
  route: SignalRoute;
  decision: OpportunityAnalysis["decision"];
  decisionReason: string;
  riskLevel: string;
  opportunityStrength: string;
  stabilityScore: number;
  dataCompleteness: number;
  buySellBalance: OpportunityAnalysis["buySellBalance"];
  entryPrice: number | null;
  targetPrice: number | null;
  expectedProfit: number | null;
  expectedLoss: number | null;
  breakEvenPrice: number | null;
  liquidationPrice: number | null;
  currentPrice: number | null;
  lastCheckedAt: Date;
  resolvedAt: Date | null;
  actualResult: SignalActualResult;
  actualNetPnl: number | null;
  engineVersion: string;
  configurationVersion: string;
  executionCostVersion: string;
};
